name: A workflow for my Hello World file
on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "offbynone"
